# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    parameters:
      image_name:
        type: string
      arch:
        type: string
      
    machine:
      image: ubuntu-2204:current
      resource_class: arm.large

    steps:
      - checkout
      - run:
          name: Build and push the image
          command: |
            github_org=${CIRCLE_PROJECT_USERNAME}
            if [[ $github_org == "yugabyte" ]]; then
              dockerhub_org="yugabyteci"
              dockerhub_user="yugabyteci"
            else
              dockerhub_org=$github_org
              dockerhub_user=$github_org
            fi
            echo "DockerHub organization: $dockerhub_org"
            echo "DockerHub user: $dockerhub_user"
            bin/build_docker_images.sh \
              -i "<< parameters.image_name >>" \
              --tag_prefix "$dockerhub_org" \
              --tag_output_file docker_tag.txt

            if [[ -z ${CIRCLE_PR_NUMBER:-} ]]; then
              echo "This is not a PR, doing a DockerHub push."
              echo "Logging into DockerHub as user '$dockerhub_user'"
              echo "${DOCKERHUB_TOKEN}" | \
                docker login -u "$dockerhub_user" --password-stdin

              docker_tag=$(<docker_tag.txt)
              echo "Docker tag: $docker_tag"
              ( set -x; docker push "$docker_tag" )
            else
              echo "This is a PR, not doing a DockerHub push."
            fi
            
  
workflows:
  build-workflow:
    jobs:
      - build:
          matrix:
            parameters:
              image_name:
                - centos7
                - almalinux8
                - almalinux9
                - ubuntu2004
                - ubuntu2204
              arch:
                - aarch64
