name: Docker

on:
  push:
    branches:
      - master

    paths-ignore:
      - README.md

  pull_request:
    branches:
      - master

    paths-ignore:
      - README.md

env:
  GITHUB_ORG_AND_REPO: "${{ github.repository }}"

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        image_name:
          - centos7
          - almalinux8
          - almalinux9
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
          - ubuntu2304

    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push' &&
       !contains(github.event.head_commit.message, 'skip ci') &&
       !contains(github.event.head_commit.message, 'ci skip') &&
       !contains(github.event.head_commit.message, 'skip gh actions') &&
       !contains(github.event.head_commit.message, 'skip github actions')) ||
      github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push the image
        run: |
          github_org=${GITHUB_ORG_AND_REPO%%/*}
          if [[ $github_org == "yugabyte" ]]; then
            dockerhub_org="yugabyteci"
            dockerhub_user="yugabyteci"
          else
            dockerhub_org=$github_org
            dockerhub_user=$github_org
          fi
          bin/build_docker_images.sh \
            -i ${{ matrix.image_name }} \
            --tag_prefix "$dockerhub_org" \
            --tag_output_file docker_tag.txt

          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Logging into DockerHub as user '$dockerhub_user'"
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
              docker login -u "$dockerhub_user" --password-stdin

            docker_tag=$(<docker_tag.txt)
            echo "Docker tag: $docker_tag"
            ( set -x; docker push "$docker_tag" )
          fi
