name: Docker

on:
  push:
    branches:
      - master

    paths-ignore:
      - README.md

  pull_request:
    branches:
      - master

    paths-ignore:
      - README.md

env:
  GITHUB_ORG_AND_REPO: "${{ github.repository }}"
  DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

jobs:
  x86_64:

    strategy:
      fail-fast: false
      matrix:
        image_name:
          - almalinux8
          - almalinux9
          - amazonlinux2
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
          - ubuntu2304
          - ubuntu2404

    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push' &&
       !contains(github.event.head_commit.message, 'skip ci') &&
       !contains(github.event.head_commit.message, 'ci skip') &&
       !contains(github.event.head_commit.message, 'skip gh actions') &&
       !contains(github.event.head_commit.message, 'skip github actions')) ||
      github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push the image
        run: |
          github_org=${GITHUB_ORG_AND_REPO%%/*}
          is_pr=true
          if [[ "${{ github.event_name }}" == "push" ]]; then
            is_pr=false
          fi
          bin/build_docker_images.sh \
            --image_name ${{ matrix.image_name }} \
            --github_org "$github_org" \
            --is_pr "$is_pr" \
            --push
