name: Docker

on:
  push:
    branches:
      - master

    paths-ignore:
      - README.md

  pull_request:
    branches:
      - master

    paths-ignore:
      - README.md

env:
  GITHUB_ORG_AND_REPO: "${{ github.repository }}"
  DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

jobs:
  x86_64:

    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: amazonlinux2
            architecture: x86_64

          - image_name: almalinux8
            architecture: x86_64

          - image_name: almalinux9
            architecture: x86_64

          - image_name: ubuntu2004
            architecture: x86_64

          - image_name: ubuntu2204
            architecture: x86_64

          - image_name: ubuntu2404
            architecture: x86_64

          - image_name: amazonlinux2
            architecture: aarch64

          - image_name: almalinux8
            architecture: aarch64

          - image_name: almalinux9
            architecture: aarch64

          - image_name: ubuntu2004
            architecture: aarch64

          - image_name: ubuntu2204
            architecture: aarch64

          - image_name: ubuntu2404
            architecture: aarch64

    runs-on: ${{ matrix.architecture == 'aarch64' && 'ubuntu-24.04-aarch64-2core-8gb' || 'ubuntu-latest' }}

    if: >
      (github.event_name == 'push' &&
       !contains(github.event.head_commit.message, 'skip ci') &&
       !contains(github.event.head_commit.message, 'ci skip') &&
       !contains(github.event.head_commit.message, 'skip gh actions') &&
       !contains(github.event.head_commit.message, 'skip github actions')) ||
      github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push the image
        run: |
          github_org=${GITHUB_ORG_AND_REPO%%/*}
          is_pr=true
          if [[ "${{ github.event_name }}" == "push" ]]; then
            is_pr=false
          fi
          bin/build_docker_images.sh \
            --image_name ${{ matrix.image_name }} \
            --github_org "$github_org" \
            --is_pr "$is_pr" \
            --push
