name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  push:

    strategy:
      matrix:
        image_name:
          - centos7
          - ubuntu1804

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >
          bin/build_docker_images.sh \
            -i ${{ matrix.image_name }} \
            --tag_user_name "${{ github.actor }}" \
            --tag_output_file docker_tag_name.txt

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push "$(<docker_tag_name.txt)"
